### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by lipilef** [DevelopersRede/magento2#14]
Versão do Magento: 2.3.2

Temos o seguinte erro ao clicar em "place order": 

```
Fatal Error: 'Uncaught Error: Class 'Rede\Environment' not found in /home/zero51carnes/public_html/app/code/Rede/Adquirencia/Model/Adapter/RedeAdapter.php:49
Stack trace:
#0 /home/zero51carnes/public_html/app/code/Rede/Adquirencia/Gateway/Http/Client/TransactionSale.php(19): Rede\Adquirencia\Model\Adapter\RedeAdapter->authorize(Array, true)
#1 /home/zero51carnes/public_html/app/code/Rede/Adquirencia/Gateway/Http/Client/AbstractTransaction.php(63): Rede\Adquirencia\Gateway\Http\Client\TransactionSale->process(Array)
#2 /home/zero51carnes/public_html/vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(106): Rede\Adquirencia\Gateway\Http\Client\AbstractTransaction->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))
#3 /home/zero51carnes/public_html/app/code/Rede/Adquirencia/Gateway/Command/CaptureStrategyCommand.php(111): Magento\Payment\Gateway\Command\GatewayCommand->execute(Array)
#4 /home/zero51carnes/public_html/vendor/magento/module-payment/Model/Method/Adapter.php(547): Rede\Adquirencia\Gateway\Co' in '/home/zero51carnes/public_html/app/code/Rede/Adquirencia/Model/Adapter/RedeAdapter.php' on line 49"``
```

**Comment by MestreMagento** [comment]
Olá @lipilef  nós desenvolvemos um módulo da e.rede com opção para cartão de crédito e débito, e disponibilizamos em nossa loja https://www.modulomagento.com.br/modulo-rede-magento-2

Temos suporte por whatsapp e mantemos nossos módulos sempre atualizados.
